# k8s/kafka/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: kafka
      tier: messaging

resources:
  - kafka-deployment.yaml
  - kafka-service.yaml
