# k8s/api/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: api
      tier: backend

resources:
  - api-deployment.yaml
  - api-service.yaml
